# Generated by Django 2.0.4 on 2018-04-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_auto_20180421_1703'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clothes',
            field=models.ManyToManyField(to='clothing.Clothing'),
        ),
    ]
