# Generated by Django 2.0.4 on 2018-04-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_name', models.CharField(max_length=250)),
                ('store_name', models.CharField(max_length=600)),
                ('clothing_type', models.CharField(max_length=600)),
                ('clothing_price', models.CharField(max_length=20)),
                ('clothing_style', models.CharField(max_length=600)),
                ('clothing_url', models.CharField(max_length=1000)),
                ('clothing_image', models.CharField(max_length=1000)),
            ],
        ),
    ]
