# Generated by Django 2.0.4 on 2018-04-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='clothing_price',
            field=models.IntegerField(),
        ),
    ]
