# Generated by Django 2.0.4 on 2018-04-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_auto_20180421_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='friendly',
            field=models.BooleanField(default=False),
        ),
    ]
